/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sys.function;

import br.sys.Bean.DadosGrafico;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author Alberto
 */
public class GerarGrafico extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerarGrafico
     */
    public GerarGrafico() {
        initComponents();
    }
      private static final long serialVersionUID = 1L;

    public GerarGrafico(String applicationTitle, String chartTitle) {
        super(applicationTitle);
        // Isso irá criar o conjunto de dados
        PieDataset dataset = createDataset();

        // com base no conjunto de dados que criamos o gráfico
        JFreeChart chart = createChart(dataset, chartTitle);

        // vamos colocar o gráfico em um painel
        ChartPanel chartPanel = new ChartPanel(chart);

        // default tamanho
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));

        // adiciona a nossa aplicação
        setContentPane(chartPanel);

    }

    /**
     * Cria um conjunto de dados de amostra
     */
    private PieDataset createDataset(DadosGrafico dados) {
        DefaultPieDataset result = new DefaultPieDataset();
        result.setValue("Entrada", dados.getEntrada());
        result.setValue("Saida", dados.getSaida());
        result.setValue("Saldo do Periodo", dados.getSaldo());
        return result;

    }

    /**
     * Cria um gráfico
     */
    private JFreeChart createChart(PieDataset dataset, String title) {

        JFreeChart chart = ChartFactory.createPieChart3D(title, // título / gráfico 
                dataset, // dados 
                true, // include lenda
                true, false);

        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        return chart;

    }

    public static void main(String[] args) {
        PieChart demo = new PieChart("Demontrativo Grafivo", "Visão dos Gasto da Empresa.");
        demo.pack();
        demo.setVisible(true);
    }

    private PieDataset createDataset() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
